### ISSUE TITLE
Enhancement: SVG with CSS transform property

### ISSUE THREAD

**Issue by MartijnKooij** [lovell/sharp#1791]
We are using SharpJS as part of Amazon's serverless image handler solution.

We are trying to dynamically resize all of our images using that service, but we are running into some issues with the results of resizing certain specific SVG files.

It might be that we need to use different resizing parameters for these, but I suspect a bug.

It is a bit difficult to explain with words, but: When we resize these SVG images it looks like only a section of the source image is being converted to PNG. As if the SVG got rendered on a huge canvas, and then the PNG is saved using a cropped area of that canvas.

Source
![math](https://svgur.com/i/E7W.svg)

Result
![math](https://user-images.githubusercontent.com/3163541/61367915-f0c76d00-a88c-11e9-9c87-f599d6fc159f.png)

I'm not familiar enough with the library yet to write an actually failing visual test, but this test at least provides at least an easy way to take the input math.svg and convert it to an output math.png which you can then visually inspect.

```javascript
const fs = require('fs');

 it('Convert SVG to PNG', function (done) {
    sharp(fixtures.bugSvg)
      .resize(1024)
      .toFormat('png')
      .toBuffer(function (err, data, info) {
        fs.writeFileSync('./test/fixtures/math.png', data);
        if (err) throw err;
        assert.strictEqual('png', info.format);
        fixtures.assertSimilar(fixtures.expected('math.png'), data, function (err) {
          if (err) throw err;
          sharp(data).metadata(function (err, info) {
            if (err) throw err;
            assert.strictEqual(72, info.density);
            done();
          });
        });
      });
  });
```

**Comment by lovell** [comment]
Hi, this is reproducible using librsvg at the command line and appears to be similar to #1550.

```sh
$ rsvg-convert -v
rsvg-convert version 2.40.20
$ rsvg-convert 1791.svg -o 1791.png
```
![1791](https://user-images.githubusercontent.com/210965/61372457-135a8580-a88f-11e9-8eec-1b091ab4f60b.png)

Please can you report this upstream at https://gitlab.gnome.org/GNOME/librsvg

**Comment by MartijnKooij** [comment]
Forwarded the issue upstream 😄 
https://gitlab.gnome.org/GNOME/librsvg/issues/487

**Comment by kleisauke** [comment]
The CSS style attributes (e.g. `style="transform:matrix(1,0,0,1,2,22.4);"`) is causing issues. Try to replace them with SVG attributes (e.g. `transform="matrix(1,0,0,1,2,22.4)"`).

For example:
```svg
<svg xmlns="http://www.w3.org/2000/svg" width="67.796875" height="28">
  <g transform="matrix(1,0,0,1,2,22.4)">
    <path d="M103 664L150 662C174 661 185 653 185 636C185 629 179 576 176 559L104 125C89 36 86 31 46 28L10 25L7 -3L39 -3L133 0L227 -3L259 -3L262 25L210 28C184 30 174 37 174 57C174 63 175 74 176 78L265 613C272 652 277 657 316 661L351 664L354 692L248 689C231 689 213 689 170 690L106 692Z" stroke="rgb(0, 0, 0)" stroke-width="8" fill="rgb(0, 0, 0)" transform="matrix(0.020399999999999998,0,0,-0.020399999999999998,0,0)"></path>
  </g>
  <g transform="matrix(1,0,0,1,14.765625,22.4)">
    <path d="M604 347L604 406L65 406L65 347ZM604 134L604 193L65 193L65 134Z" stroke="rgb(0, 0, 0)" stroke-width="8" fill="rgb(0, 0, 0)" transform="matrix(0.020399999999999998,0,0,-0.020399999999999998,0,0)"></path>
  </g>
  <g transform="matrix(1,0,0,1,34.390625,22.4)">
    <path d="M280 181L280 106C280 46 269 32 220 30L158 27L158 -3C291 0 291 0 315 0C339 0 339 0 472 -3L472 27L424 30C375 33 364 46 364 106L364 181C423 181 444 180 472 177L472 248L364 245L365 697L285 667L2 204L2 181ZM280 245L65 245L280 597ZM1024 42C968 42 963 125 964 166C965 251 993 333 1036 405L1098 418C1101 435 1107 452 1112 467C958 461 799 463 644 466C579 467 565 389 546 340C545 332 558 331 562 328L562 332C605 395 629 405 704 405L727 405C687 266 660 129 597 -2L597 -12C617 -6 652 1 669 13C710 141 739 274 767 405L994 405C937 318 896 213 894 108C894 59 909 -15 970 -15C1011 -15 1067 25 1097 51L1097 66L1085 66L1085 67C1067 56 1047 42 1024 42ZM1520 365C1523 403 1528 435 1536 476C1525 481 1521 482 1516 482C1485 482 1454 458 1418 407C1379 351 1340 291 1324 256L1356 408C1360 425 1362 438 1362 450C1362 470 1354 482 1339 482C1318 482 1280 461 1206 408L1178 388L1185 368L1217 389C1245 407 1256 412 1265 412C1275 412 1282 403 1282 390C1282 332 1239 126 1199 -2L1209 -9C1224 -4 1240 -1 1263 4L1276 6L1302 126C1320 209 1343 262 1387 319C1421 363 1448 384 1470 384C1485 384 1495 379 1506 365Z" stroke="rgb(0, 0, 0)" stroke-width="8" fill="rgb(0, 0, 0)" transform="matrix(0.020399999999999998,0,0,-0.020399999999999998,0,0)"></path>
  </g>
</svg>
```
![1791](https://user-images.githubusercontent.com/12746591/61376608-ca5ffc80-a8a1-11e9-89d7-7dca8ce1c4bd.png)
(tested with librsvg 2.45.7)

Note that you can further optimize these SVG files with [SVGO](https://github.com/svg/svgo):
```svg
<svg xmlns="http://www.w3.org/2000/svg" width="67.797" height="28">
  <path d="M4.101 8.854l.959.041c.49.02.714.184.714.53 0 .143-.122 1.225-.184 1.571L4.122 19.85c-.306 1.816-.368 1.918-1.184 1.979l-.734.061-.061.571h.653l1.917-.061 1.918.061h.653l.06-.571-1.06-.061c-.53-.041-.734-.184-.734-.592 0-.122.02-.347.04-.428L7.406 9.895c.143-.796.245-.898 1.04-.98l.714-.06.062-.572-2.163.061c-.347 0-.714 0-1.591-.02l-1.306-.04zm22.986 6.467v-1.203H16.092v1.203zm0 4.345v-1.203H16.092v1.203zm13.016-.958v1.53c0 1.224-.225 1.51-1.224 1.55l-1.265.061v.612c2.713-.061 2.713-.061 3.203-.061.49 0 .49 0 3.202.061v-.612l-.979-.061c-1-.061-1.224-.326-1.224-1.55v-1.53c1.204 0 1.632.02 2.203.081v-1.448l-2.203.061.02-9.22-1.631.611-5.774 9.445v.47zm0-1.306h-4.386l4.386-7.18zm15.177 4.141c-1.142 0-1.244-1.693-1.224-2.53.02-1.733.592-3.406 1.469-4.875l1.265-.265c.061-.347.183-.694.285-1-3.141.123-6.385.082-9.547.02-1.326-.02-1.611 1.571-1.999 2.571-.02.163.245.184.326.245v-.082c.878-1.285 1.367-1.489 2.897-1.489h.47c-.817 2.836-1.367 5.63-2.653 8.303v.204c.408-.123 1.122-.265 1.47-.51.836-2.611 1.427-5.325 1.998-7.997h4.631c-1.163 1.775-1.999 3.917-2.04 6.059 0 1 .306 2.509 1.55 2.509.837 0 1.98-.816 2.591-1.346v-.306h-.244v-.02c-.368.224-.776.51-1.245.51zm10.12-6.589c.06-.775.163-1.428.326-2.264-.224-.102-.306-.123-.408-.123-.632 0-1.265.49-2 1.53-.795 1.143-1.59 2.367-1.917 3.08l.653-3.1a3.74 3.74 0 0 0 .122-.857c0-.408-.163-.653-.469-.653-.428 0-1.203.429-2.713 1.51l-.571.408.143.408.652-.429c.572-.367.796-.469.98-.469.204 0 .346.184.346.449 0 1.183-.877 5.386-1.693 7.997l.204.143c.306-.102.633-.164 1.102-.266l.265-.04.53-2.448c.368-1.694.837-2.775 1.734-3.938.694-.897 1.245-1.326 1.694-1.326.306 0 .51.102.734.388z" stroke="#000" stroke-width=".163"/>
</svg>
```
(you can try it online [here](https://jakearchibald.github.io/svgomg/))

**Comment by MartijnKooij** [comment]
Thanks @kleisauke if no other solutions are available we could write a lambda@edge function that detects and modifies these types of errors. Or if we find that it’s just a few of the thousands of images we serve, then we could manually fix them, but we would rather not touch them.

@lovell the reply on the librsvg issue does not really mean anything to me. Is Sharp depending on an old version and could this be solved by upgrading something? Or am I wishfully oversimplifying the problem?

**Comment by lovell** [comment]
@MartijnKooij The canned reply is requesting that you try to reproduce this problem on a newer version of librsvg. I've just tried with librsvg v2.45.5 and still see the problem.

You will need to install the latest version of librsvg, currently v2.45.7, and prove that the `rsvg-convert` tool it provides fails in the same manner with your sample input then update/reopen the upstream bug.

**Comment by MartijnKooij** [comment]
(Luckily) one of the project maintainers beat me to it and verified that the behavior also occurs on the master branch. I will monitor the issue and post any updated back here.

**Comment by lovell** [comment]
It looks like this has been implemented upstream via https://gitlab.gnome.org/GNOME/librsvg/-/merge_requests/576

The v0.30.0 release of sharp will include prebuilt binaries with a version of librsvg > 2.52.0

**Comment by lovell** [comment]
v0.30.0 now available with prebuilt binaries that include a version of librsvg with the upstream fix.
