### ISSUE TITLE
Error: extract_area: bad extract area

### ISSUE THREAD

**Issue by erhankilic** [lovell/sharp#688]
Hello, I'm using 512x512 image. First I resize it then extract and expecting readable stream data but it shows me "Error: extract_area: bad extract area" error.
Here's the code;

```
test2(x, y, zoom) {
        const width = 500;
        const height = 500;

        return this.image
            .metadata()
            .then((metadata) => {
                var resizedWidth = metadata.width * zoom;
                var resizedHeight = metadata.height * zoom;
                var left = parseInt(resizedWidth * x);
                var top = parseInt(resizedHeight * y);
                return this.image
                    .resize(resizedWidth, resizedHeight)
                    .extract({left: left, top: top, width: width, height: height})
                    .jpeg()
                    .resize(500);
            });
}
```
Thanks.

**Comment by erhankilic** [comment]
Ahhh, I must say, resizedWidth = 1024, resizedHeight = 1024 (because i used zoom = 0,5) and left = 204, right = 204 (because i used x = 0,2 and y = 0,2). Extract area is valid.

**Comment by lovell** [comment]
Hello, I think the problem here is that `.resize(500)` will replace the values passed to `.resize(resizedWidth, resizedHeight)`. Whilst you can chain `extract` with `resize` (with `extract`), you can't chain `resize` with itself.

If you need the output image to always be 500 pixels wide, you might be able to extract-then-resize via `.extract(...).resize(500, resizedHeight)`, making sure to alter your `resizedHeight` calculation accordingly.

**Comment by erhankilic** [comment]
Ahhh, thanks,

I fixed it with this codes.

```
return this.image
            .metadata()
            .then((metadata) => {
                var resizedWidth = metadata.width * zoom;
                var resizedHeight = metadata.height * zoom;
                var left = parseInt(resizedWidth * x);
                var top = parseInt(resizedHeight * y);
                return this.image
                    .jpeg()
                    .resize(resizedWidth, resizedHeight)
                    .toBuffer()
                    .then((data) => {
                        return sharp(data)
                            .extract({left: left, top: top, width: width, height: height})
                            .resize(width, height);
                    })
            });
```

**Comment by CorfitzMe** [comment]
I know this may be an old thread - but I experienced this issue recently, and it was due to the orientation of the image on the server, not being equivalent of the interpreted orientation in the browser. Say I took a picture with my iPhone, then safari and the phone knew how to properly orient the photo, but the server no.

In order to fix that, I simply initialised the sharp procedure with `.rotate()`, which took care of that. 

`sharp('image data goes here').rotate().extract({left: left, top: top, width: width, height: height}).resize(width, height);`.

Just as a note for future visitors, as this issue pops up as the first result when searching in Google.

**Comment by hunzaGit** [comment]
Thanks to @imCorfitz 's comment I solved the problem, for some strange reason Sharp (v0.25.4) interprets some rotated images, in particular a vertical image taken from the smartphone's gallery. If the frontend of the app gets the picture (vertical or horizontal) from the camera everything works fine.

In my case, simply comparing the Sharp Metadata with the original dimensions of the photo fixed it.

As a simple code example:
```
if(dimOriginal.width === metadata.height && dimOriginal.height === metadata.width){
    console.log("image is rotated");
    promiseImg = promiseImg.rotate()
}
```

**Comment by geiszla** [comment]
This is still an issue until this day. Is there an issue tracking this?
